### ISSUE TITLE
The land is too rich in minerals?

### ISSUE THREAD

**Issue by j34ni** [Quickbeasts51429/Outreachy_Galaxy_Community_contributor#10]
Do you mean that there are **too much** minerals? or that the land is **also** rich in minerals (i.e., in addition to other things)?

**Comment by Quickbeasts51429** [comment]
> Do you mean that there are **too much** minerals? or that the land is **also** rich in minerals (i.e., in addition to other things)?

Like 17% of the entire country's iron ore comes from this state...but ya the tone of the statement I wrote is kinda weird. I'll change it to .."The land is also rich in minerals."

**Comment by Quickbeasts51429** [comment]
I've edited the content.

**Comment by j34ni** [comment]
We can close this issue then

**Comment by Quickbeasts51429** [comment]
Thanks
