### ISSUE TITLE
Min-max on regional plots

### ISSUE THREAD

**Issue by annefou** [Quickbeasts51429/Outreachy_Galaxy_Community_contributor#2]
So now that we see all the regional plots on a page (https://quickbeasts51429.github.io/Outreachy_Galaxy_Community_contributor/regional.html ), we see that the lower bound could have been increased. So maybe a range of values between 270 and 305 (or even 310) would be better.

**Comment by Quickbeasts51429** [comment]
You're absolutely right...after some hours the entire region becomes reddish with no distinction between temperatures...I'll do it as soon as possible..Thanks!


> So now that we see all the regional plots on a page (https://quickbeasts51429.github.io/Outreachy_Galaxy_Community_contributor/regional.html ), we see that the lower bound could have been increased. So maybe a range of values between 270 and 305 (or even 310) would be better.

**Comment by Quickbeasts51429** [comment]
I've made the changes for this issue. Kindly look into it once. Then would close the issue.

**Comment by annefou** [comment]
Yes! And I see that you have also updated the title with the local time! Awesome!
