### ISSUE TITLE
Add references whenever you can

### ISSUE THREAD

**Issue by annefou** [Quickbeasts51429/Outreachy_Galaxy_Community_contributor#3]
You added very interesting information/facts; for instaance 

>  India has experienced hottest month of March in 122 years with 71% rain deficit.

It would be awesome to add  where you got this information. This always help readers to trust what we write.

You can also add links to external website providing further information. For instance if some want to know more about the Deccan Ålateau, etc.

**Comment by Quickbeasts51429** [comment]
I've made the changes for this issue. Kindly look into it once. Then would close the issue.

**Comment by annefou** [comment]
👍 I will have a follow-up question on references but let's close that one. Thanks!
