### ISSUE TITLE
list of temperatures for different hours on 24-03-2022

### ISSUE THREAD

**Issue by annefou** [Quickbeasts51429/Outreachy_Galaxy_Community_contributor#4]
It would be really nice to indicate the location itself, name of the city or area. you could also add a link to read more about the location.

**Comment by annefou** [comment]
I see you have done it. that's great. 
I have issues with links on your pages: they do not appear as clickable links while they are in the html code. Is it a problem with my we browser? Do you know?

**Comment by Quickbeasts51429** [comment]
Yes...there's a problem with anchor tag there...am working on it...once I complete ..I'll let you know for review. Probable I'll be done in next two hours.


> I see you have done it. that's great. I have issues with links on your pages: they do not appear as clickable links while they are in the html code. Is it a problem with my we browser? Do you know?

**Comment by Quickbeasts51429** [comment]
I've made the changes for this issue. Kindly look into it once. Then would close the issue.

**Comment by annefou** [comment]
Yes! That'awesome. Well done 🎉
