### ISSUE TITLE
Jharkhand

### ISSUE THREAD

**Issue by annefou** [Quickbeasts51429/Outreachy_Galaxy_Community_contributor#6]
> What durations of the days would be most uncomfortable for the workers around mines?

Here we have only information for March 24, 2022 so we can not generalize but you can say that for that particular day, this would be better for the workers to work between X and Y.

**Comment by Quickbeasts51429** [comment]
These are great suggestions...Thanks a lot for such amazing  reviews..

**Comment by Quickbeasts51429** [comment]
I've made the changes for this issue. Kindly look into it once. Then would close the issue.

**Comment by annefou** [comment]
> I've made the changes for this issue. Kindly look into it once. Then would close the issue.

👍
