### ISSUE TITLE
How to cite references

### ISSUE THREAD

**Issue by annefou** [Quickbeasts51429/Outreachy_Galaxy_Community_contributor#8]
I added some information in the outreachy channel about it (see https://www.student.unsw.edu.au/harvard-referencing)

**Comment by Quickbeasts51429** [comment]
While referencing in website, would the hyperlinking be sufficient? Or should we follow the citation guideline and list out the references sequentially like we do in a review or a research paper?

**Comment by annefou** [comment]
If your source is from a scientific paper, you can cite it following citation guideline for scientific research paper but if it is from wikipedia, just mention it in parenthesis. Does it make sense?

**Comment by Quickbeasts51429** [comment]
> If your source is from a scientific paper, you can cite it following citation guideline for scientific research paper but if it is from wikipedia, just mention it in parenthesis. Does it make sense?

Of course it does...I understood thanks!

**Comment by annefou** [comment]
Then you can record your contribution for Q5 in outreachy. Well done! 🎉

**Comment by Quickbeasts51429** [comment]
> Then you can record your contribution for Q5 in outreachy. Well done! 🎉

That's great...am currently working on that...as soon as I finish..I'll record the contribution.....Thank you so much for being such an amazing mentor!!

**Comment by annefou** [comment]
By the way I just noticed that (in insights) you have one question "What is Data Structure?". I think the title of the question does not match the answer.

**Comment by Quickbeasts51429** [comment]
> By the way I just noticed that (in insights) you have one question "What is Data Structure?". I think the title of the question does not match the answer.

Yes...am working on that...that's a dummy question for now...am adding that cashew and wine stuff there
It will be done by today

**Comment by annefou** [comment]
That's awesome! Just submit your contribution to outreachy when you are done (no need to wait for anyone to confirm). You have done a very good job. thanks..

**Comment by Quickbeasts51429** [comment]
> That's awesome! Just submit your contribution to outreachy when you are done (no need to wait for anyone to confirm). You have done a very good job. thanks..

Thank you so much!!

**Comment by Quickbeasts51429** [comment]
I've made the changes...if no changes have to be done, then you can close the issue.

**Comment by annefou** [comment]
Awesome. 
One thing we will have to be careful with, is the usage of images on website. We are not allowed to reproduce images on our own website. Here you have your own copyright for your website (which is great) and then you have to be extra careful. 

https://www.student.unsw.edu.au/citing-images-and-tables-found-online does not explain much about it. But don't worry, this is something we can address in the future. 

I close the issue.

**Comment by Quickbeasts51429** [comment]
Oh..yes...I've tried to include most of the images which are royalty free,
mostly from Canva.com. But ya..there are some like..2-4 which I took
directly from websites....will surely find an alternative to that. Thanks!
