### ISSUE TITLE
Link to your Galaxy History

### ISSUE THREAD

**Issue by annefou** [Quickbeasts51429/Outreachy_Galaxy_Community_contributor#9]
One last thing: could you also add the link to your public Galaxy history? Thanks a lot.

**Comment by annefou** [comment]
And add your Galaxy history as a contribution to outreachy. I don't think I have seen the history with ERA5 data analysis.

**Comment by Quickbeasts51429** [comment]
Yes..surely I'll do that

**Comment by Quickbeasts51429** [comment]
> One last thing: could you also add the link to your public Galaxy history? Thanks a lot.

https://usegalaxy.eu/u/soumyajha9090/h/ecmwf-era5-reanalysistask4-1

**Comment by Quickbeasts51429** [comment]
> And add your Galaxy history as a contribution to outreachy. I don't think I have seen the history with ERA5 data analysis.

Yes...before that please have a look on my history and do suggest if any thing  should be improved.

**Comment by annefou** [comment]
> > One last thing: could you also add the link to your public Galaxy history? Thanks a lot.
> 
> https://usegalaxy.eu/u/soumyajha9090/h/ecmwf-era5-reanalysistask4-1

The last montage is not public (I cannot see it). Fix the access for this dataset and then you can share it. You have done a very good job.

**Comment by Quickbeasts51429** [comment]
> 

okay..I'll fix that..Thanks!

> > > One last thing: could you also add the link to your public Galaxy history? Thanks a lot.
> > 
> > 
> > https://usegalaxy.eu/u/soumyajha9090/h/ecmwf-era5-reanalysistask4-1
> 
> The last montage is not public (I cannot see it). Fix the access for this dataset and then you can share it. You have done a very good job.

**Comment by Quickbeasts51429** [comment]
https://usegalaxy.eu/u/soumyajha9090/h/ecmwf-era5-reanalysistask4-1          
I guess its visible now...please confirm

**Comment by annefou** [comment]
No it is still not visible.

**Comment by Quickbeasts51429** [comment]
https://usegalaxy.eu/u/soumyajha9090/h/ecmwf-era5-reanalysistask4-1

**Comment by annefou** [comment]
Perfect!

**Comment by annefou** [comment]
So we can close this issue (don't forget to add the link in outreachy!).

**Comment by Quickbeasts51429** [comment]
For sure...
